services:
  postgres:
    image: postgres:15.2-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pg_secret
    working_dir: /app
    volumes:
      - db:/var/lib/postgresql/data
      - ./sql/:/app/sql/

  pgadmin:
    image: dpage/pgadmin4:7.7
    ports:
      - '443:443'
    volumes:
      - pgadmin4:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@example.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
      - PGADMIN_LISTEN_PORT=443
    depends_on:
      - postgres

volumes:
  db:
  pgadmin4:
